export const services = [
{slug:'social-media-marketing',title:'Social Media Marketing',items:['Instagram Marketing','Facebook Marketing','LinkedIn Marketing','Twitter/X Marketing','Social Media Management','Content Posting','Reels Marketing','Audience Engagement','Brand Awareness','Social Media Strategy','Viral Content Planning']},
{slug:'smma-account-handling',title:'SMMA / Account Handling',items:['Daily Post Management','Monthly Content Planning','Caption Writing','Hashtag Research','Story Management','DM Management','Page Growth Strategy','Content Scheduling','Analytics Monitoring','Client Account Handling']},
{slug:'meta-ads',title:'Meta Ads / Facebook Ads',items:['Lead Generation Ads','Conversion Ads','WhatsApp Ads','Traffic Campaigns','Retargeting Ads','Instagram Ads','Facebook Ads','Video Ads','Carousel Ads','Sales Campaigns','Pixel Setup','Audience Targeting']},
{slug:'google-ads',title:'Google Ads',items:['Search Ads','Display Ads','Shopping Ads','YouTube Ads','App Promotion Ads','Local Business Ads','Remarketing Campaigns','Keyword Research','Conversion Tracking','PPC Campaign Management']},
{slug:'paid-marketing',title:'Paid Marketing',items:['Paid Campaign Setup','Paid Traffic Generation','Ad Funnel Strategy','Campaign Optimization','Budget Management','Ad Copywriting','Landing Page Optimization','ROI Improvement']},
{slug:'performance-marketing',title:'Performance Marketing',items:['ROI Based Campaigns','Cost Per Lead Optimization','Conversion Rate Optimization','Sales Funnel Marketing','Data Driven Marketing','Analytics Reporting','Customer Acquisition','Revenue Growth Campaigns']},
{slug:'youtube-marketing',title:'YouTube Marketing',items:['YouTube SEO','Thumbnail Design','Video Ranking','Channel Branding','YouTube Ads','Watch Time Strategy','Subscriber Growth','Viral Strategy','Shorts Marketing','Video Optimization']},
{slug:'lead-generation',title:'Lead Generation',items:['Business Leads','Real Estate Leads','Education Leads','Healthcare Leads','WhatsApp Leads','Sales Funnel Leads','B2B Lead Generation','High Intent Leads','Landing Page Leads']},
{slug:'branding-creative-design',title:'Branding & Creative Design',items:['Logo Design','Banner Design','Social Media Creatives','Ad Creatives','Brand Identity Design','Packaging Design','Business Card Design','Brochure Design','Motion Graphics','Creative Strategy']},
{slug:'website-development',title:'Website Development',items:['Business Website','Portfolio Website','Landing Page','E-commerce Website','WordPress Website','UI/UX Design','Website Redesign','Website Optimization','Mobile Responsive Design','Speed Optimization']},
{slug:'seo',title:'SEO',items:['On Page SEO','Off Page SEO','Technical SEO','Local SEO','E-commerce SEO','YouTube SEO','Keyword Research','Backlink Building','Google Ranking','SEO Audit']},
{slug:'ecommerce-marketing',title:'E-commerce Marketing',items:['Shopify Marketing','Product Ads','Amazon Marketing','Flipkart Marketing','Shopping Campaigns','Product Branding','Store Optimization','Sales Funnel Setup','Product SEO','E-commerce Growth Strategy']},
{slug:'ai-marketing-services',title:'AI Marketing Services',items:['AI Content Creation','AI Ad Creatives','AI Video Generation','AI Chatbots','AI Automation','AI Copywriting','AI Voiceovers','AI Image Generation','AI Marketing Strategy','AI Customer Support']},
{slug:'automation-services',title:'Automation Services',items:['WhatsApp Automation','Instagram Automation','Email Automation','CRM Automation','Lead Automation','Chatbot Setup','Auto Reply Systems','Workflow Automation','Business Process Automation']},
{slug:'saas-app-development',title:'SaaS App Development',items:['SaaS Product Planning','Admin Dashboard','Subscription System','User Management','Payment Integration','API Development','Cloud Deployment','Analytics Dashboard','MVP Development','Product Scaling']},
{slug:'mobile-app-development',title:'Mobile App Development',items:['Android App Development','Flutter App Development','App UI/UX','Play Store Setup','App Dashboard','Push Notifications','API Integration','App Maintenance','MVP Apps','Business Apps']},
{slug:'thumbnail-creative-design',title:'Thumbnail / Creative Design',items:['YouTube Thumbnails','Podcast Thumbnails','Reels Covers','Banner Design','Gaming Thumbnails','News Thumbnails','Clickbait Thumbnails','Creative Posters','Promotional Creatives','Thumbnail Optimization']}
]
export const industries = [
{slug:'real-estate-marketing',title:'Real Estate Marketing'}, {slug:'education-marketing',title:'Coaching & Education Marketing'}, {slug:'healthcare-marketing',title:'Healthcare Marketing'}, {slug:'local-business-marketing',title:'Local Business Marketing'}, {slug:'ecommerce-growth',title:'E-commerce Growth'}, {slug:'personal-brand-growth',title:'Personal Brand Growth'}]
export const products = ['MeriAsk Review Booster','MeriAsk Social Scheduler','ClipForge','Okay KRC PG Manager','Business Calculator Toolkit','Convertix Pro','QR Barcode Scanner','Varasko AI']
