export type City = { slug: string; name: string; state: string; intro: string; sectors: string[]; angle: string; tip: [string, string] }

export const cities: City[] = [
  { slug: 'jaipur', name: 'Jaipur', state: 'Rajasthan',
    intro: 'Jaipur is MeriAsk’s home city. Our office is in Jaisinghpura, Bhankrota, so Jaipur businesses can meet us in person as well as work with us online.',
    sectors: ['Tourism and hospitality', 'Jewellery and handicrafts', 'Real estate', 'Textiles and block-print fashion', 'Coaching and education'],
    angle: 'Many Jaipur customers check Google Maps, reviews and Instagram before they call or visit, so local SEO and strong visual content usually come first.',
    tip: ['What works best for a local Jaipur shop or service?', 'Start with a fully optimized Google Business Profile, regular Instagram content and a small Meta or Google Ads budget aimed at nearby areas. Track calls and WhatsApp inquiries so you can see what brings customers.'] },
  { slug: 'jodhpur', name: 'Jodhpur', state: 'Rajasthan',
    intro: 'Jodhpur businesses, from furniture and handicraft sellers to hotels and service providers, often sell to customers far beyond the city. MeriAsk helps them reach those buyers online.',
    sectors: ['Handicrafts and furniture', 'Tourism and hotels', 'Textiles', 'Real estate'],
    angle: 'Exporters and craft sellers need a fast, English-first website with product SEO, while hotels and local services benefit from Maps visibility and reviews.',
    tip: ['How can a Jodhpur handicraft or furniture seller reach buyers outside the city?', 'Build a product-focused website with clear photos and inquiry forms, add product SEO, and use Google Ads and Instagram to reach buyers in other cities and countries.'] },
  { slug: 'udaipur', name: 'Udaipur', state: 'Rajasthan',
    intro: 'Udaipur’s economy leans on tourism, weddings and hospitality. MeriAsk helps hotels, planners, photographers and local brands turn browsing into bookings.',
    sectors: ['Hotels and resorts', 'Destination weddings and event planners', 'Handicrafts and souvenirs', 'Real estate'],
    angle: 'Travellers and wedding clients compare options online, so photography, reviews, Instagram Reels and a clear booking or inquiry path make a big difference.',
    tip: ['How can a wedding or hospitality business in Udaipur get more inquiries?', 'Show real work through Reels and galleries, collect reviews, make WhatsApp inquiry one tap away, and run targeted ads to audiences planning events or trips.'] },
  { slug: 'kota', name: 'Kota', state: 'Rajasthan',
    intro: 'Kota is widely known as a coaching hub, and its institutes, hostels and PGs depend on timely admissions. MeriAsk helps education businesses in Kota plan campaigns around the admission cycle.',
    sectors: ['Coaching institutes', 'Student hostels and PGs', 'Study material and edtech', 'Food and student services'],
    angle: 'Admission-season lead generation, demo-class funnels, parent-focused content and quick WhatsApp follow-up are especially important here.',
    tip: ['How should a Kota coaching institute or PG promote itself?', 'Combine local SEO and Maps for nearby searches with Meta lead ads for demo classes, and follow up on every inquiry quickly on WhatsApp.'] },
  { slug: 'delhi-ncr', name: 'Delhi NCR', state: 'Delhi, Haryana and Uttar Pradesh',
    intro: 'Delhi NCR, including Gurugram and Noida, is a large and competitive market. MeriAsk helps businesses here improve return from every rupee of ad spend with better funnels and tracking.',
    sectors: ['Startups and B2B services', 'Real estate', 'Healthcare and clinics', 'E-commerce and D2C brands'],
    angle: 'Because competition and ad costs can be high, conversion tracking, landing pages and lead quality matter more than simply spending more.',
    tip: ['How do we compete in a crowded market like Delhi NCR?', 'Focus on a specific niche or locality, build landing pages tailored to the offer, track lead quality, and improve the funnel before scaling budgets.'] },
  { slug: 'mumbai', name: 'Mumbai', state: 'Maharashtra',
    intro: 'Mumbai’s businesses range from professional services and finance to real estate, entertainment and D2C brands. MeriAsk supports them with performance marketing, websites and automation.',
    sectors: ['Professional and financial services', 'Real estate', 'D2C and e-commerce', 'Creators and personal brands'],
    angle: 'Speed matters in Mumbai, so fast websites, sharp positioning and quick lead follow-up help businesses stand out.',
    tip: ['What should a Mumbai service business prioritize first?', 'A clear offer, a fast landing page, conversion tracking and instant WhatsApp or email follow-up, then scale ads once you know your cost per lead.'] },
  { slug: 'bengaluru', name: 'Bengaluru', state: 'Karnataka',
    intro: 'Bengaluru is a hub for startups, software and technology companies. MeriAsk’s mix of marketing and product development suits founders who need both users and software.',
    sectors: ['SaaS and software startups', 'IT and B2B services', 'D2C brands', 'Education and skilling'],
    angle: 'SaaS and B2B teams here benefit from content marketing, SEO, LinkedIn and structured lead generation alongside product development.',
    tip: ['Can you help a Bengaluru startup with both product and marketing?', 'Yes. We can scope and build an MVP or dashboard and also set up SEO, landing pages and campaigns to acquire early users.'] },
  { slug: 'hyderabad', name: 'Hyderabad', state: 'Telangana',
    intro: 'Hyderabad has strong IT, pharma and life sciences sectors along with growing real estate, education and healthcare. MeriAsk helps these businesses build trust and generate inquiries online.',
    sectors: ['IT and B2B services', 'Pharma and healthcare', 'Real estate', 'Education'],
    angle: 'Trust-heavy sectors like healthcare and B2B services benefit from informative content, reviews and credible websites.',
    tip: ['How can a Hyderabad clinic or B2B firm build online trust?', 'Publish helpful content, keep Google Business Profile and reviews strong, and use a clear, professional website with schema and contact options.'] },
  { slug: 'pune', name: 'Pune', state: 'Maharashtra',
    intro: 'Pune combines IT, manufacturing, education and a vibrant startup community. MeriAsk supports businesses here with SEO, ads, websites and automation.',
    sectors: ['IT and software', 'Manufacturing and engineering', 'Education and coaching', 'Startups'],
    angle: 'Manufacturers and B2B firms often need lead generation and technical SEO, while education and startups lean on content and paid campaigns.',
    tip: ['How can a Pune manufacturer or B2B company get quality leads?', 'Build product and industry pages with clear specifications, target buyers with Google Ads and LinkedIn, and set up a CRM or sheet to follow up systematically.'] },
  { slug: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat',
    intro: 'Ahmedabad has a large base of traders, manufacturers and small and mid-sized businesses. MeriAsk helps them move from word-of-mouth to steady digital inquiries.',
    sectors: ['Textiles and trading', 'Manufacturing and chemicals', 'Real estate', 'SMEs and retail'],
    angle: 'Catalog websites, WhatsApp-based inquiry flows and Google Ads for high-intent searches work well for trading and manufacturing businesses.',
    tip: ['How can an Ahmedabad trader or manufacturer get online inquiries?', 'Create a clear product catalog website, optimize it for search, run Google Ads on buying keywords and make WhatsApp inquiries easy.'] },
  { slug: 'surat', name: 'Surat', state: 'Gujarat',
    intro: 'Surat is known for textiles and diamonds and has a strong base of wholesalers and online sellers. MeriAsk helps them grow online sales and reach retailers and consumers across India.',
    sectors: ['Textiles and apparel', 'Diamonds and jewellery', 'Wholesale and resellers', 'E-commerce sellers'],
    angle: 'Product catalogs, marketplace and shopping campaigns, and catalog-style WhatsApp flows suit sellers who move many products.',
    tip: ['How can a Surat textile or jewellery seller sell beyond the city?', 'Use a strong catalog site or store, Google Shopping and Meta catalog ads, marketplace marketing, and WhatsApp for wholesale inquiries.'] },
  { slug: 'indore', name: 'Indore', state: 'Madhya Pradesh',
    intro: 'Indore has a strong food and retail culture along with growing education, real estate and IT. MeriAsk helps local brands and service businesses grow their visibility and customer base.',
    sectors: ['Food brands and restaurants', 'Retail and trading', 'Education and coaching', 'Real estate'],
    angle: 'Food and retail businesses benefit from Maps, Instagram and delivery-focused campaigns, while education and property lean on lead generation.',
    tip: ['How can an Indore food brand or restaurant grow online?', 'Optimize Google Maps, post consistent Reels, encourage reviews and run local ads that drive orders, visits or WhatsApp inquiries.'] },
]
